
version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    
      # - EMAIL_USER=${EMAIL_USER}
      # - EMAIL_PASS =${EMAIL_PASS}
      # - EMAIL_HOST=${EMAIL_HOST}
      # - EMAIL_PORT=${EMAIL_PORT}
    # volumes:
    #   - /app/node_modules
    restart: unless-stopped
